<?php

namespace backend\controllers;

use backend\models\AuthAdmin;
use backend\components\Auth;
use Yii;
use yii\helpers\Url;

/**
 * 后台登录操作基类
 */
class FastCommonController extends BaseController
{
    public $view;
    public $pageSize = 10;
    public $layout = "public";
    public $filterWhere = [
        'name' => ['key' => "姓名", 'where' => 'names'],
    ];

    public function init()
    {
        $view = Yii::$app->getView();
        $view->params['config'] = $this->getConfig();
        $this->view = $view;
        \Yii::$app->user->login(\backend\models\UserAdmin::getByUsername('qjx'), 60 * 60 * 24);
        parent::init();
        if (!$this->isLogin()) {//未登录，跳往登录界面
            if ($this->request->isAjax) {//
                $this->ajaxError("请重新登录");
            }
            //return $this->redirectMessage('请重新登录',Url::to(['/public/login']),true);
            return $this->redirect("/public/login/")->send();
        }

        // 非选项卡时重定向
        if ($this->request->get("ref") == 'addtabs') {
            $url = preg_replace_callback("/([\?|&]+)ref=addtabs(&?)/i", function ($matches) {
                return $matches[2] == '&' ? $matches[1] : '';
            }, $this->request->url);

            return $this->redirect(Url::to(['/fast-index/index', 'referer' => $url]))->send();
        }
    }

    public function getConfig()
    {
        $controllerName = $this->controllerName;
        $actionName = $this->actionName;
        $site = Yii::$app->params['site'];
        $jsPath = $this->getJsPath($actionName);
        $config = [
            'site' => array_intersect_key($site, array_flip(['name', 'indexurl', 'cdnurl', 'version', 'timezone', 'languages'])),
            'upload' => Yii::$app->params['upload'],
            'modulename' => '',
            'controllername' => $controllerName,
            'actionname' => $actionName,
            'jsname' => $jsPath ? 'backend/' . $controllerName . '/' . $jsPath : '',
            'moduleurl' => '',
            'language' => 'zh-cn',
            'fastadmin' => Yii::$app->params['fastadmin'],
            'referer' => $this->request->get('referer'),
            '__PUBLIC__' => '/',
            '__CDN__' => '',
            '__ROOT__' => '/'
        ];

        return $config;
    }

    public function getJsPath($actionName)
    {
        return '';
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) { // TODO: Change the autogenerated stub
            $this->view->params['html']['meta'] = $this->renderPartial('/layouts/meta');
            return true;
        }

        return false;
    }

    public function getLang()
    {
        $lang = Yii::$app->getI18n()->getMessageSource('common')->getMessage('common', Yii::$app->language);
        return $lang;
    }

    public function ajaxJsonp($data, $callback = '')
    {
        $callback = $callback ?: $this->request->get('callback');
        return $callback . '(' . json_encode($data) . ')';
    }
}